Fix Julia 1.0 compat in tests
Julia 1.0 does not allow type definitions in local scopes,
in this case the `@testset` and throws this error:

ERROR: LoadError: error compiling top-level scope: type definition not allowed inside a local scope

The type definition has been moved outside of the `@testset` macro.